### ISSUE TITLE
Test "deleteUser" mutation

### ISSUE THREAD

**Issue by Sddilora** [octoposprime/op-be-gw#33]
Test the "deleteUser" mutation with all possible cases and create an issue if any bugs are found. If you encounter unexpected behavior or are unsure if it is intended, please create an issue for that as well.

**You can find an example issue and bug report (or a question if this is a bug) in [this link](https://github.com/octoposprime/op-be-graphql/issues/20).**

"[Test GraphQL Query and Mutation](https://github.com/octoposprime/op-be-graphql/discussions/35)" guide is available for further assistance.

**Comment by Feyzanrs** [comment]
![Ekran görüntüsü 2024-04-20 111209](https://github.com/octoposprime/op-be-graphql/assets/141928475/2f4db0ff-6e33-4239-b691-1ef9534c50e3)
![Ekran görüntüsü 2024-04-20 111242](https://github.com/octoposprime/op-be-graphql/assets/141928475/7f9952c2-7c3c-4425-8c2f-c51cd2c9d3f8)
I encountered an issue while testing the 'deleteUser' mutation. When I perform a deletion with an invalid user ID, the behavior of the API is different from what's expected. Even though no such user exists, the mutation operation returns the queried ID but does not return the username. It makes sense for the username to be returned empty because the user does not exist; however, shouldn't the API return an error message saying 'User not found' for a non-existent user?

cretaed issue for that : #47

**Comment by Sddilora** [comment]
There appears to be a discrepancy in the behavior of the `deleteUser` mutation. When attempting to delete a user with an invalid ID, the API returns the queried ID without the corresponding username, without providing any indication of why the deletion failed.

While it's understandable that the username would be empty since the user doesn't exist, returning the fact that the user doesn't exist could pose a security risk. It's important not to divulge information about the existence or non-existence of users in responses, as this could potentially aid attackers in their attempts to enumerate valid user IDs.

Therefore, while it's necessary to provide feedback regarding deletion failures, it's crucial not to disclose information about the existence of users. Instead, the API response should indicate that the deletion couldn't be performed without specifying the reason. This approach maintains both security and user privacy while still providing necessary feedback to the user.
